Fixing performance issue related with querydsl spatial on hibernate.
OpenFeign/querydsl pull request #369
Opened 2024-04-06 11:44 UTC by dcuestam

As the representation of the operations were doing an equal true (boolean check), the DB engine is not able to use the spatial index, and instead of performing the intersects with the entities using the spatial index and comparing only the ones indicated by this one, was applying the intersects operation to all the entities.

How was discovered?

While migrating my application from native spatial queries to querydsl-spatial I found a big downgrade on the performance. Analysing the differences between the native queries that I had and the ones generated by querydsl-spatial, I was able to indentify that queryDSL spatial was adding for most of the operations that I was interested on an = true clause. It is not needed and this comparison makes the db engine to not to use the spatial index on those queries.

it can be easily analysed by an EXPLAIN clause, that would show that using = true/false, the spatial index is not used, but without this clause, it is used, having exactly the same result in the queries.

In my case, the performance issue was of having queries executed in few milliseconds to more than 10 minutes in some cases

2024-04-06 13:48 UTC, velo requested changes
As discussed in slack, can you add some unit tests on the serializer, so we guarantee won't be a regression in the future?

2024-04-06 14:18 UTC, dcuestam commented
> As discussed in slack, can you add some unit tests on the serializer, so we guarantee won't be a regression in the future?

Done! you can check it

2024-04-06 16:38 UTC, velo approved these changes

2024-04-06 16:38 UTC, merged

2024-04-07 01:05 UTC, velo commented
Port of https://github.com/querydsl/querydsl/pull/3718