Fix AbstractR2DBCQuery Fetch Method
OpenFeign/querydsl pull request #490
Opened 2024-07-07 05:14 UTC by xeounxzxu

# Changed to explicitly cancel R2DBC connection pool

@velo 

issue number :  https://github.com/OpenFeign/querydsl/issues/352

background : 

This code gets the db connection via `getConnection` and performs operations within `flatMapMany`. 

as-is: 
However, there is no explicit connection termination in the current version. There is no code to return to the connection pool, which can result in a resource leak. 

to-be:
Use Flux.usingWhen to acquire a connection, and when done, call the (`Connection::close`) method to close the connection and return. 
Because this method explicitly closes the connection, we've changed the resource management to allow for safe termination.

2024-07-31 12:04 UTC, velo approved these changes

2024-07-31 12:06 UTC, velo requested changes
Seems this change breaks a bunch of tests...

2024-08-02 15:52 UTC, closed without merging

2024-08-02 15:52 UTC, velo commented
For now, going to close this as tests are no passing.

2024-08-03 01:16 UTC, xeounxzxu commented
@velo  Sorry for the late reply. I will upload it again after changing the test case.